// MessageService: the base class every RPC service extends.
//
// A service is named on the bus by ServiceName(), normally its .proto
// `<package>.<Service>`. It owns one durable queue of that name, bound to
// REQUEST.<ServiceName>.*, which every replica consumes from, so the broker
// balances load and fails over. It also owns `<ServiceName>.Events` for the
// events it subscribes to.
//
// Code generated by the protobus-cpp CLI (or protoc-gen-protobus-cpp)
// derives a `<Service>Base` class from this one with a virtual method per
// rpc; implement those. Without codegen, derive from MessageService directly
// and register handlers over dynamic messages with registerMethod().
//
// A service is owned by a std::shared_ptr (std::make_shared, or
// RunnableService::start): each delivery holds a reference while its handler
// runs, so a service released mid-request is destroyed once that request is
// done, never under a running handler.
//
// A handler's exception decides what happens to the request. A HandledError
// is an answer: it reaches the caller with its code and is never retried.
// Anything else, or a processing timeout, is a failure: the request is retried
// through the service's retry queue and dead-lettered once retries are spent,
// and the caller is answered then.
#pragma once

#include <condition_variable>
#include <functional>
#include <map>
#include <memory>
#include <mutex>
#include <optional>
#include <set>
#include <string>

#include <google/protobuf/descriptor.h>
#include <google/protobuf/message.h>

#include "protobus/cancel_listener.h"
#include "protobus/context.h"
#include "protobus/custom_types.h"
#include "protobus/errors.h"
#include "protobus/event_listener.h"
#include "protobus/generator.h"
#include "protobus/message_listener.h"

namespace protobus {

namespace detail {
struct HandlerTurn;
}

struct MessageServiceOptions {
  // Deliveries handled in parallel by this process: the queue's prefetch.
  // Default 1.
  std::optional<int> maxConcurrent;
  RetryOptions retry;
  // Ack after the handler completes (the default) rather than on delivery.
  // Acking on delivery disables retry, dead-lettering and error replies: set
  // it false only for genuine at-most-once delivery.
  std::optional<bool> lateAck;
  // Per-request processing timeout. Default Config::messageProcessingTimeout().
  std::optional<int64_t> processingTimeoutMs;
  // Declare the request queue as a priority queue with this x-max-priority.
  // Left unset, the queue arguments are unchanged.
  std::optional<int> maxPriority;
  // Retry for this service's EVENT subscriptions; off by default.
  EventRetryOptions eventRetry;
  // Run this service's handlers one at a time: requests, each step of a
  // stream, and events never overlap, so the service's own state needs no
  // locking. Off by default (handlers run in parallel on worker threads).
  // Time spent waiting for the turn counts against processingTimeoutMs, and a
  // handler that calls its own service and waits for the reply throws
  // std::logic_error instead of deadlocking. See docs/threading.md.
  bool serializeHandlers = false;
};

// What a handler receives besides its request.
struct CallContext {
  // Free-text caller identity from the request envelope. Not authenticated.
  std::string actor;
  std::string correlationId;
  // The contract method, "<package>.<Service>.<method>".
  std::string method;
  // Fires on the processing timeout and, for a stream, when the caller
  // cancels. Watch it in long or cancellable work.
  AbortSignal signal;
  // The routing key the broker delivered on.
  std::string routingKey;
  // Stable across redeliveries and retries: deduplicate on it.
  std::string messageId;
  bool redelivered = false;
  const amqp::FieldTable* headers = nullptr;
};

class MessageService : public std::enable_shared_from_this<MessageService> {
 public:
  explicit MessageService(Context& context, MessageServiceOptions options = {});
  virtual ~MessageService();

  MessageService(const MessageService&) = delete;
  MessageService& operator=(const MessageService&) = delete;

  // The service's name on the bus. Several instances can share one schema
  // under distinct names ("Combat.Player.player6" serving the contract
  // "Combat.Player"): the contract is found by trimming trailing segments
  // until one names a loaded service.
  virtual std::string ServiceName() const = 0;
  // The .proto file declaring the service, for a schema that is neither
  // compiled in nor loaded from a proto directory. Default: none.
  virtual std::string ProtoFileName() const;
  // The schema text: ProtoFileName()'s contents. Throws MissingProto.
  virtual std::string Proto() const;

  // Register the schema if needed, declare the queues and start consuming.
  // Throws std::logic_error unless the service is owned by a shared_ptr.
  virtual void init();
  // Stop accepting new requests and events, leaving channels open so work in
  // hand can finish: the first step of a graceful shutdown. Pair it with
  // Connection::drainInFlight() before closing anything.
  void stopConsuming();
  // Stop consuming and close the service's channels.
  void close();

  void publishEvent(const std::string& type, const google::protobuf::Message& content, const std::string& topic = "");
  void publishEvent(const google::protobuf::Message& content, const std::string& topic = "");
  // Subscribe this service to events. Call after init().
  void subscribeEvent(const std::string& type, EventHandler handler, const std::string& topic = "");
  template <typename T>
  void subscribeEvent(std::function<void(const T&, const std::string&, const std::string&)> handler,
                      const std::string& topic = "") {
    eventListener_->subscribe<T>(std::move(handler), topic);
  }

  // The contract this service serves, once init() has resolved it.
  std::string contractServiceName() const;
  Context& context() const { return context_; }

 protected:
  using UnaryMethod =
      std::function<std::unique_ptr<google::protobuf::Message>(const google::protobuf::Message&, CallContext&)>;
  using StreamMethod = std::function<Generator<std::unique_ptr<google::protobuf::Message>>(
      const google::protobuf::Message&, CallContext&)>;

  // Dynamic handlers: the request is a dynamic message of the contract's
  // request type, and the result must be of its response type.
  void registerMethod(const std::string& name, UnaryMethod handler);
  void registerStreamingMethod(const std::string& name, StreamMethod handler);

  // Typed handlers, as generated code registers them.
  template <typename Req, typename Res>
  void registerUnary(const std::string& name, std::function<Res(const Req&, CallContext&)> handler) {
    MethodEntry entry;
    entry.streaming = false;
    entry.unary = [handler, name](const std::string& payload, CallContext& ctx) {
      Req request;
      parseRequest(request, payload, ctx.method);
      Res result = handler(request, ctx);
      return MessageFactory::encodeMessage(result);
    };
    addMethod(name, std::move(entry));
  }

  template <typename Req, typename Res>
  void registerStream(const std::string& name, std::function<Generator<Res>(const Req&, CallContext&)> handler) {
    MethodEntry entry;
    entry.streaming = true;
    entry.stream = [handler](const std::string& payload, std::shared_ptr<CallContext> ctx) {
      auto request = std::make_shared<Req>();
      parseRequest(*request, payload, ctx->method);
      return runTypedStream<Req, Res>(std::move(request), std::move(ctx), handler);
    };
    addMethod(name, std::move(entry));
  }

  // Parse a request, answering malformed bytes as PROTOCOL_ERROR: the same
  // bytes fail the same way on every redelivery, so they are never retried.
  static void parseRequest(google::protobuf::Message& request, const std::string& payload,
                           const std::string& method);

 private:
  struct MethodEntry {
    bool streaming = false;
    std::function<std::string(const std::string& payload, CallContext& ctx)> unary;
    std::function<Generator<std::string>(const std::string& payload, std::shared_ptr<CallContext> ctx)> stream;
  };
  // The request and context live in this frame for as long as the handler's
  // generator does: its body runs after the call that created it returns.
  template <typename Req, typename Res>
  static Generator<std::string> runTypedStream(std::shared_ptr<Req> request, std::shared_ptr<CallContext> ctx,
                                               std::function<Generator<Res>(const Req&, CallContext&)> handler) {
    Generator<Res> chunks = handler(*request, *ctx);
    while (auto chunk = chunks.next()) co_yield MessageFactory::encodeMessage(*chunk);
  }

  void addMethod(const std::string& name, MethodEntry entry);
  void registerSchema();
  bool tryResolveContract();
  void resolveContract();
  MessageHandlerResult onMessage(const std::string& data, const std::string& correlationId,
                                 MessageHandlerContext& context);
  std::string protocolError(const std::string& label, const std::string& reason) const;
  std::string handleUnaryError(const std::string& method, std::exception_ptr error, const std::string& correlationId);
  std::optional<std::string> buildTimeoutReply(const std::string& content, const std::exception& error) const;

  Context& context_;
  MessageServiceOptions options_;
  std::shared_ptr<MessageListener> listener_;
  std::shared_ptr<EventListener> eventListener_;
  std::shared_ptr<CancelListener> cancelListener_;
  // Held by every handler when options_.serializeHandlers is on.
  std::shared_ptr<detail::HandlerTurn> turn_;

  mutable std::mutex mutex_;
  std::map<std::string, MethodEntry> methods_;
  std::optional<std::string> contractServiceName_;
  std::set<std::string> declaredMethods_;
  bool initialized_ = false;
};

}  // namespace protobus
