#include "generator.h"

#include <google/protobuf/compiler/cpp/names.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/printer.h>
#include <google/protobuf/io/zero_copy_stream.h>

#include <memory>
#include <set>
#include <sstream>

namespace protobus::codegen {

namespace gpb = google::protobuf;

namespace {

const std::set<std::string>& cppKeywords() {
  static const std::set<std::string> k = {
      "alignas",   "alignof",      "and",        "and_eq",    "asm",          "auto",      "bitand",
      "bitor",     "bool",         "break",      "case",      "catch",        "char",      "char8_t",
      "char16_t",  "char32_t",     "class",      "compl",     "concept",      "const",     "consteval",
      "constexpr", "constinit",    "const_cast", "continue",  "co_await",     "co_return", "co_yield",
      "decltype",  "default",      "delete",     "do",        "double",       "dynamic_cast", "else",
      "enum",      "explicit",     "export",     "extern",    "false",        "float",     "for",
      "friend",    "goto",         "if",         "inline",    "int",          "long",      "mutable",
      "namespace", "new",          "noexcept",   "not",       "not_eq",       "nullptr",   "operator",
      "or",        "or_eq",        "private",    "protected", "public",       "register",  "reinterpret_cast",
      "requires",  "return",       "short",      "signed",    "sizeof",       "static",    "static_assert",
      "static_cast", "struct",     "switch",     "template",  "this",         "thread_local", "throw",
      "true",      "try",          "typedef",    "typeid",    "typename",     "union",     "unsigned",
      "using",     "virtual",      "void",       "volatile",  "wchar_t",      "while",     "xor",
      "xor_eq",
  };
  return k;
}

// Members of RunnableService / MessageService and of the generated proxy
// that an rpc of the same name would hide.
const std::set<std::string>& reservedMembers() {
  static const std::set<std::string> r = {
      "init",          "close",          "stopConsuming",   "ServiceName",   "ProtoFileName",
      "Proto",         "publishEvent",   "subscribeEvent",  "contractServiceName", "context",
      "cleanup",       "start",          "wait",            "requestShutdown", "setExitAfterShutdown",
      "registerMethod", "registerStreamingMethod", "registerUnary", "registerStream", "parseRequest",
      "kServiceName",  "raw",            "serviceName",
  };
  return r;
}

std::string stripProto(const std::string& name) {
  const std::string ext = ".proto";
  if (name.size() > ext.size() && name.compare(name.size() - ext.size(), ext.size(), ext) == 0) {
    return name.substr(0, name.size() - ext.size());
  }
  return name;
}

std::string typeName(const gpb::Descriptor* d) { return gpb::compiler::cpp::QualifiedClassName(d); }

void openNamespace(gpb::io::Printer& p, const std::string& ns) {
  if (!ns.empty()) p.Print("namespace $ns$ {\n\n", "ns", ns);
}

void closeNamespace(gpb::io::Printer& p, const std::string& ns) {
  if (!ns.empty()) p.Print("}  // namespace $ns$\n", "ns", ns);
}

void generateHeader(const gpb::FileDescriptor* file, gpb::io::Printer& p) {
  const std::string base = stripProto(std::string(file->name()));
  p.Print(
      "// Generated by protoc-gen-protobus-cpp. DO NOT EDIT.\n"
      "// source: $file$\n"
      "#pragma once\n\n"
      "#include <string>\n\n"
      "#include <protobus/protobus.h>\n\n"
      "#include \"$base$.pb.h\"\n\n",
      "file", std::string(file->name()), "base", base);

  const std::string ns = packageNamespace(std::string(file->package()));
  openNamespace(p, ns);
  for (int s = 0; s < file->service_count(); ++s) {
    const auto* service = file->service(s);
    const std::string name(service->name());
    const std::string full(service->full_name());

    p.Print(
        "// $full$, as a service: derive from $name$Base and override its rpcs.\n"
        "// An rpc left unimplemented answers PROTOCOL_ERROR.\n"
        "class $name$Base : public ::protobus::RunnableService {\n"
        " public:\n"
        "  static constexpr const char* kServiceName = \"$full$\";\n\n"
        "  explicit $name$Base(::protobus::Context& context, ::protobus::MessageServiceOptions options = {});\n\n"
        "  std::string ServiceName() const override { return kServiceName; }\n",
        "full", full, "name", name);
    for (int m = 0; m < service->method_count(); ++m) {
      const auto* method = service->method(m);
      const std::string id = methodIdentifier(std::string(method->name()));
      const std::string req = typeName(method->input_type());
      const std::string res = typeName(method->output_type());
      p.Print("\n  // rpc $proto$($in$) returns ($stream$$out$);\n", "proto", std::string(method->name()), "in",
              std::string(method->input_type()->full_name()), "stream",
              method->server_streaming() ? "stream " : "", "out", std::string(method->output_type()->full_name()));
      if (method->client_streaming()) {
        p.Print("  // Client streaming is not part of the protobus protocol; this rpc is not served.\n");
        continue;
      }
      if (method->server_streaming()) {
        p.Print("  virtual ::protobus::Generator<$res$> $id$(const $req$& request, ::protobus::CallContext& context);\n",
                "res", res, "id", id, "req", req);
      } else {
        p.Print("  virtual $res$ $id$(const $req$& request, ::protobus::CallContext& context);\n", "res", res, "id",
                id, "req", req);
      }
    }
    p.Print("};\n\n");

    p.Print(
        "// A typed client of $full$.\n"
        "class $name$Proxy {\n"
        " public:\n"
        "  static constexpr const char* kServiceName = \"$full$\";\n\n"
        "  // `serviceName` addresses an instance registered under a longer name.\n"
        "  explicit $name$Proxy(::protobus::Context& context, std::string serviceName = kServiceName);\n\n"
        "  // Resolve the contract. Call once, after Context::init().\n"
        "  void init();\n"
        "  ::protobus::ServiceProxy& raw() { return proxy_; }\n",
        "full", full, "name", name);
    for (int m = 0; m < service->method_count(); ++m) {
      const auto* method = service->method(m);
      if (method->client_streaming()) continue;
      const std::string id = methodIdentifier(std::string(method->name()));
      const std::string req = typeName(method->input_type());
      const std::string res = typeName(method->output_type());
      if (method->server_streaming()) {
        p.Print(
            "  ::protobus::Stream<$res$> $id$(const $req$& request, const ::protobus::StreamOptions& options = {});\n",
            "res", res, "id", id, "req", req);
      } else {
        p.Print("  $res$ $id$(const $req$& request, const ::protobus::CallOptions& options = {});\n", "res", res,
                "id", id, "req", req);
      }
    }
    p.Print(
        "\n private:\n"
        "  ::protobus::ServiceProxy proxy_;\n"
        "};\n\n");
  }
  closeNamespace(p, ns);
}

void generateSource(const gpb::FileDescriptor* file, gpb::io::Printer& p) {
  const std::string base = stripProto(std::string(file->name()));
  p.Print(
      "// Generated by protoc-gen-protobus-cpp. DO NOT EDIT.\n"
      "// source: $file$\n"
      "#include \"$base$.protobus.h\"\n\n"
      "#include <utility>\n\n",
      "file", std::string(file->name()), "base", base);
  const std::string ns = packageNamespace(std::string(file->package()));
  openNamespace(p, ns);
  for (int s = 0; s < file->service_count(); ++s) {
    const auto* service = file->service(s);
    const std::string name(service->name());

    p.Print(
        "$name$Base::$name$Base(::protobus::Context& context, ::protobus::MessageServiceOptions options)\n"
        "    : ::protobus::RunnableService(context, std::move(options)) {\n",
        "name", name);
    for (int m = 0; m < service->method_count(); ++m) {
      const auto* method = service->method(m);
      if (method->client_streaming()) continue;
      const std::string id = methodIdentifier(std::string(method->name()));
      const std::string req = typeName(method->input_type());
      const std::string res = typeName(method->output_type());
      p.Print(
          "  register$kind$<$req$, $res$>(\"$proto$\", [this](const $req$& request, ::protobus::CallContext& ctx) {\n"
          "    return this->$id$(request, ctx);\n"
          "  });\n",
          "kind", method->server_streaming() ? "Stream" : "Unary", "req", req, "res", res, "proto",
          std::string(method->name()), "id", id);
    }
    p.Print("}\n\n");

    for (int m = 0; m < service->method_count(); ++m) {
      const auto* method = service->method(m);
      if (method->client_streaming()) continue;
      const std::string id = methodIdentifier(std::string(method->name()));
      const std::string req = typeName(method->input_type());
      const std::string res = typeName(method->output_type());
      if (method->server_streaming()) {
        p.Print(
            "::protobus::Generator<$res$> $name$Base::$id$(const $req$&, ::protobus::CallContext&) {\n"
            "  throw ::protobus::InvalidMethodError(\"invalid service method $proto$\");\n"
            "}\n\n",
            "res", res, "name", name, "id", id, "req", req, "proto", std::string(method->name()));
      } else {
        p.Print(
            "$res$ $name$Base::$id$(const $req$&, ::protobus::CallContext&) {\n"
            "  throw ::protobus::InvalidMethodError(\"invalid service method $proto$\");\n"
            "}\n\n",
            "res", res, "name", name, "id", id, "req", req, "proto", std::string(method->name()));
      }
    }

    p.Print(
        "$name$Proxy::$name$Proxy(::protobus::Context& context, std::string serviceName)\n"
        "    : proxy_(context, std::move(serviceName)) {}\n\n"
        "void $name$Proxy::init() { proxy_.init(); }\n\n",
        "name", name);
    for (int m = 0; m < service->method_count(); ++m) {
      const auto* method = service->method(m);
      if (method->client_streaming()) continue;
      const std::string id = methodIdentifier(std::string(method->name()));
      const std::string req = typeName(method->input_type());
      const std::string res = typeName(method->output_type());
      if (method->server_streaming()) {
        p.Print(
            "::protobus::Stream<$res$> $name$Proxy::$id$(const $req$& request, const ::protobus::StreamOptions& "
            "options) {\n"
            "  return proxy_.callStreamTyped<$res$>(\"$proto$\", request, options);\n"
            "}\n\n",
            "res", res, "name", name, "id", id, "req", req, "proto", std::string(method->name()));
      } else {
        p.Print(
            "$res$ $name$Proxy::$id$(const $req$& request, const ::protobus::CallOptions& options) {\n"
            "  return proxy_.callTyped<$res$>(\"$proto$\", request, options);\n"
            "}\n\n",
            "res", res, "name", name, "id", id, "req", req, "proto", std::string(method->name()));
      }
    }
  }
  closeNamespace(p, ns);
}

}  // namespace

std::string methodIdentifier(const std::string& protoName) {
  if (cppKeywords().count(protoName) || reservedMembers().count(protoName)) return protoName + "_";
  return protoName;
}

std::string packageNamespace(const std::string& package) {
  std::string out;
  for (char c : package) {
    if (c == '.') {
      out += "::";
    } else {
      out.push_back(c);
    }
  }
  return out;
}

bool ProtobusGenerator::Generate(const gpb::FileDescriptor* file, const std::string&,
                                 gpb::compiler::GeneratorContext* context, std::string* error) const {
  const std::string base = stripProto(std::string(file->name()));
  {
    std::unique_ptr<gpb::io::ZeroCopyOutputStream> out(context->Open(base + ".protobus.h"));
    gpb::io::Printer printer(out.get(), '$');
    generateHeader(file, printer);
    if (printer.failed()) {
      *error = "failed writing " + base + ".protobus.h";
      return false;
    }
  }
  {
    std::unique_ptr<gpb::io::ZeroCopyOutputStream> out(context->Open(base + ".protobus.cc"));
    gpb::io::Printer printer(out.get(), '$');
    generateSource(file, printer);
    if (printer.failed()) {
      *error = "failed writing " + base + ".protobus.cc";
      return false;
    }
  }
  return true;
}

}  // namespace protobus::codegen
